// <auto-generated />
using System;
using System.Collections.Generic;
using Cutline.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Cutline.Infrastructure.Migrations
{
    [DbContext(typeof(CutlineDbContext))]
    [Migration("20260315220632_AddManagerIsAdmin")]
    partial class AddManagerIsAdmin
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Cutline.Core.Entities.ChatMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("GifUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("LeagueId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ManagerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ManagerId");

                    b.HasIndex("LeagueId", "SentAt");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("Cutline.Core.Entities.Draft", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CurrentPickNumber")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CurrentPickStartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LeagueId")
                        .HasColumnType("uuid");

                    b.Property<int>("PickTimeLimitSeconds")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LeagueId");

                    b.ToTable("Drafts");
                });

            modelBuilder.Entity("Cutline.Core.Entities.DraftPick", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DraftId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsAutoPick")
                        .HasColumnType("boolean");

                    b.Property<int>("PickNumber")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("PickedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<int>("Round")
                        .HasColumnType("integer");

                    b.Property<int>("RoundPick")
                        .HasColumnType("integer");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("TeamId");

                    b.HasIndex("DraftId", "PickNumber")
                        .IsUnique();

                    b.ToTable("DraftPicks");
                });

            modelBuilder.Entity("Cutline.Core.Entities.League", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Season")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "RosterSettings", "Cutline.Core.Entities.League.RosterSettings#RosterSettings", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("BenchSlots")
                                .HasColumnType("integer");

                            b1.Property<int>("DefSlots")
                                .HasColumnType("integer");

                            b1.Property<decimal>("FaabBudget")
                                .HasColumnType("numeric");

                            b1.Property<int>("FlexSlots")
                                .HasColumnType("integer");

                            b1.Property<int>("IrSlots")
                                .HasColumnType("integer");

                            b1.Property<int>("KSlots")
                                .HasColumnType("integer");

                            b1.Property<decimal>("MinFaabBid")
                                .HasColumnType("numeric");

                            b1.Property<int>("QbSlots")
                                .HasColumnType("integer");

                            b1.Property<int>("RbSlots")
                                .HasColumnType("integer");

                            b1.Property<int>("SuperFlexSlots")
                                .HasColumnType("integer");

                            b1.Property<bool>("TePremium")
                                .HasColumnType("boolean");

                            b1.Property<int>("TeSlots")
                                .HasColumnType("integer");

                            b1.Property<bool>("UseFaab")
                                .HasColumnType("boolean");

                            b1.Property<int>("WrSlots")
                                .HasColumnType("integer");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "ScoringSettings", "Cutline.Core.Entities.League.ScoringSettings#ScoringSettings", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("FumbleLostPoints")
                                .HasColumnType("numeric");

                            b1.Property<decimal>("InterceptionPoints")
                                .HasColumnType("numeric");

                            b1.Property<decimal>("PassingTdPoints")
                                .HasColumnType("numeric");

                            b1.Property<decimal>("PassingYardsPerPoint")
                                .HasColumnType("numeric");

                            b1.Property<decimal>("ReceivingTdPoints")
                                .HasColumnType("numeric");

                            b1.Property<decimal>("ReceivingYardsPerPoint")
                                .HasColumnType("numeric");

                            b1.Property<decimal>("ReceptionPoints")
                                .HasColumnType("numeric");

                            b1.Property<decimal>("RushingTdPoints")
                                .HasColumnType("numeric");

                            b1.Property<decimal>("RushingYardsPerPoint")
                                .HasColumnType("numeric");
                        });

                    b.HasKey("Id");

                    b.ToTable("Leagues");
                });

            modelBuilder.Entity("Cutline.Core.Entities.LeagueManager", b =>
                {
                    b.Property<Guid>("LeagueId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ManagerId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsCommissioner")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("LeagueId", "ManagerId");

                    b.HasIndex("ManagerId");

                    b.ToTable("LeagueManagers");
                });

            modelBuilder.Entity("Cutline.Core.Entities.Manager", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Managers");
                });

            modelBuilder.Entity("Cutline.Core.Entities.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("Adp")
                        .HasPrecision(7, 2)
                        .HasColumnType("numeric(7,2)");

                    b.Property<int?>("Age")
                        .HasColumnType("integer");

                    b.Property<int?>("ByeWeek")
                        .HasColumnType("integer");

                    b.Property<string>("College")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("DepthChartOrder")
                        .HasColumnType("integer");

                    b.Property<string>("EspnId")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("GsisId")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Height")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int?>("JerseyNumber")
                        .HasColumnType("integer");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset>("LastSyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NflTeam")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("SleeperId")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Weight")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int?>("YearsExperience")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EspnId");

                    b.HasIndex("GsisId")
                        .IsUnique();

                    b.HasIndex("SleeperId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("Cutline.Core.Entities.PlayerGameStats", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("DefensiveInterceptions")
                        .HasColumnType("integer");

                    b.Property<int?>("DefensiveTDs")
                        .HasColumnType("integer");

                    b.Property<int?>("ExtraPointsAttempted")
                        .HasColumnType("integer");

                    b.Property<int?>("ExtraPointsMade")
                        .HasColumnType("integer");

                    b.Property<int?>("FieldGoalsAttempted")
                        .HasColumnType("integer");

                    b.Property<int?>("FieldGoalsMade")
                        .HasColumnType("integer");

                    b.Property<int?>("Fumbles")
                        .HasColumnType("integer");

                    b.Property<int?>("FumblesRecovered")
                        .HasColumnType("integer");

                    b.Property<string>("GameStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Interceptions")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("LongFieldGoal")
                        .HasColumnType("integer");

                    b.Property<string>("Opponent")
                        .HasColumnType("text");

                    b.Property<int?>("PassingAttempts")
                        .HasColumnType("integer");

                    b.Property<int?>("PassingCompletions")
                        .HasColumnType("integer");

                    b.Property<int?>("PassingTDs")
                        .HasColumnType("integer");

                    b.Property<int?>("PassingYards")
                        .HasColumnType("integer");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Points")
                        .HasColumnType("decimal(8,2)");

                    b.Property<int?>("PointsAllowed")
                        .HasColumnType("integer");

                    b.Property<int?>("ReceivingTDs")
                        .HasColumnType("integer");

                    b.Property<int?>("ReceivingYards")
                        .HasColumnType("integer");

                    b.Property<int?>("Receptions")
                        .HasColumnType("integer");

                    b.Property<int?>("RushingAttempts")
                        .HasColumnType("integer");

                    b.Property<int?>("RushingTDs")
                        .HasColumnType("integer");

                    b.Property<int?>("RushingYards")
                        .HasColumnType("integer");

                    b.Property<int?>("Sacks")
                        .HasColumnType("integer");

                    b.Property<int?>("Safeties")
                        .HasColumnType("integer");

                    b.Property<int>("Season")
                        .HasColumnType("integer");

                    b.Property<int?>("Targets")
                        .HasColumnType("integer");

                    b.Property<int>("WeekNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId", "Season", "WeekNumber")
                        .IsUnique();

                    b.ToTable("PlayerGameStats");
                });

            modelBuilder.Entity("Cutline.Core.Entities.RosterSlot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsStarter")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<int>("SlotType")
                        .HasColumnType("integer");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("TeamId");

                    b.ToTable("RosterSlots");
                });

            modelBuilder.Entity("Cutline.Core.Entities.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("EliminatedWeek")
                        .HasColumnType("integer");

                    b.Property<bool>("IsEliminated")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("boolean");

                    b.Property<Guid>("LeagueId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ManagerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("OwnerUserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("ManagerId");

                    b.HasIndex("LeagueId", "ManagerId")
                        .IsUnique()
                        .HasFilter("\"ManagerId\" IS NOT NULL");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("Cutline.Core.Entities.TeamScore", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Points")
                        .HasColumnType("numeric");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WeekId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.HasIndex("WeekId", "TeamId")
                        .IsUnique();

                    b.ToTable("TeamScores");
                });

            modelBuilder.Entity("Cutline.Core.Entities.Trade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("InitiatorTeamId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LeagueId")
                        .HasColumnType("uuid");

                    b.Property<string>("Message")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("ProposedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ReceiverTeamId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("RespondedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LeagueId");

                    b.HasIndex("InitiatorTeamId", "Status");

                    b.HasIndex("ReceiverTeamId", "Status");

                    b.ToTable("Trades");
                });

            modelBuilder.Entity("Cutline.Core.Entities.TradeItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("FromTeamId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TradeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("TradeId");

                    b.ToTable("TradeItems");
                });

            modelBuilder.Entity("Cutline.Core.Entities.WaiverClaim", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AddPlayerId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DropPlayerId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("FaabBid")
                        .HasColumnType("numeric");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WeekId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AddPlayerId");

                    b.HasIndex("DropPlayerId");

                    b.HasIndex("TeamId");

                    b.HasIndex("WeekId");

                    b.ToTable("WaiverClaims");
                });

            modelBuilder.Entity("Cutline.Core.Entities.Week", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<Guid[]>("DroppedPlayerIds")
                        .IsRequired()
                        .HasColumnType("uuid[]");

                    b.Property<Guid?>("EliminatedTeamId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LeagueId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("WeekNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EliminatedTeamId");

                    b.HasIndex("LeagueId", "WeekNumber")
                        .IsUnique();

                    b.ToTable("Weeks");
                });

            modelBuilder.Entity("Cutline.Core.Entities.ChatMessage", b =>
                {
                    b.HasOne("Cutline.Core.Entities.Manager", "Manager")
                        .WithMany()
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("Cutline.Core.Entities.Draft", b =>
                {
                    b.HasOne("Cutline.Core.Entities.League", "League")
                        .WithMany()
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("League");
                });

            modelBuilder.Entity("Cutline.Core.Entities.DraftPick", b =>
                {
                    b.HasOne("Cutline.Core.Entities.Draft", "Draft")
                        .WithMany("Picks")
                        .HasForeignKey("DraftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cutline.Core.Entities.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Cutline.Core.Entities.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Draft");

                    b.Navigation("Player");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Cutline.Core.Entities.LeagueManager", b =>
                {
                    b.HasOne("Cutline.Core.Entities.League", "League")
                        .WithMany("LeagueManagers")
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cutline.Core.Entities.Manager", "Manager")
                        .WithMany("LeagueManagers")
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("League");

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("Cutline.Core.Entities.PlayerGameStats", b =>
                {
                    b.HasOne("Cutline.Core.Entities.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Cutline.Core.Entities.RosterSlot", b =>
                {
                    b.HasOne("Cutline.Core.Entities.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId");

                    b.HasOne("Cutline.Core.Entities.Team", "Team")
                        .WithMany("RosterSlots")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Cutline.Core.Entities.Team", b =>
                {
                    b.HasOne("Cutline.Core.Entities.League", "League")
                        .WithMany("Teams")
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cutline.Core.Entities.Manager", "Manager")
                        .WithMany("Teams")
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("League");

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("Cutline.Core.Entities.TeamScore", b =>
                {
                    b.HasOne("Cutline.Core.Entities.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cutline.Core.Entities.Week", "Week")
                        .WithMany("TeamScores")
                        .HasForeignKey("WeekId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");

                    b.Navigation("Week");
                });

            modelBuilder.Entity("Cutline.Core.Entities.Trade", b =>
                {
                    b.HasOne("Cutline.Core.Entities.Team", "InitiatorTeam")
                        .WithMany()
                        .HasForeignKey("InitiatorTeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cutline.Core.Entities.Team", "ReceiverTeam")
                        .WithMany()
                        .HasForeignKey("ReceiverTeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InitiatorTeam");

                    b.Navigation("ReceiverTeam");
                });

            modelBuilder.Entity("Cutline.Core.Entities.TradeItem", b =>
                {
                    b.HasOne("Cutline.Core.Entities.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Cutline.Core.Entities.Trade", "Trade")
                        .WithMany("Items")
                        .HasForeignKey("TradeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Trade");
                });

            modelBuilder.Entity("Cutline.Core.Entities.WaiverClaim", b =>
                {
                    b.HasOne("Cutline.Core.Entities.Player", "AddPlayer")
                        .WithMany()
                        .HasForeignKey("AddPlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Cutline.Core.Entities.Player", "DropPlayer")
                        .WithMany()
                        .HasForeignKey("DropPlayerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Cutline.Core.Entities.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Cutline.Core.Entities.Week", "Week")
                        .WithMany("WaiverClaims")
                        .HasForeignKey("WeekId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AddPlayer");

                    b.Navigation("DropPlayer");

                    b.Navigation("Team");

                    b.Navigation("Week");
                });

            modelBuilder.Entity("Cutline.Core.Entities.Week", b =>
                {
                    b.HasOne("Cutline.Core.Entities.Team", "EliminatedTeam")
                        .WithMany()
                        .HasForeignKey("EliminatedTeamId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Cutline.Core.Entities.League", "League")
                        .WithMany("Weeks")
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EliminatedTeam");

                    b.Navigation("League");
                });

            modelBuilder.Entity("Cutline.Core.Entities.Draft", b =>
                {
                    b.Navigation("Picks");
                });

            modelBuilder.Entity("Cutline.Core.Entities.League", b =>
                {
                    b.Navigation("LeagueManagers");

                    b.Navigation("Teams");

                    b.Navigation("Weeks");
                });

            modelBuilder.Entity("Cutline.Core.Entities.Manager", b =>
                {
                    b.Navigation("LeagueManagers");

                    b.Navigation("Teams");
                });

            modelBuilder.Entity("Cutline.Core.Entities.Team", b =>
                {
                    b.Navigation("RosterSlots");
                });

            modelBuilder.Entity("Cutline.Core.Entities.Trade", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Cutline.Core.Entities.Week", b =>
                {
                    b.Navigation("TeamScores");

                    b.Navigation("WaiverClaims");
                });
#pragma warning restore 612, 618
        }
    }
}
