// <auto-generated />
using System;
using System.Collections.Generic;
using Cutline.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Cutline.Infrastructure.Migrations
{
    [DbContext(typeof(CutlineDbContext))]
    [Migration("20260314202446_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Cutline.Core.Entities.League", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Season")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "RosterSettings", "Cutline.Core.Entities.League.RosterSettings#RosterSettings", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("BenchSlots")
                                .HasColumnType("integer");

                            b1.Property<int>("DefSlots")
                                .HasColumnType("integer");

                            b1.Property<int>("FlexSlots")
                                .HasColumnType("integer");

                            b1.Property<int>("IrSlots")
                                .HasColumnType("integer");

                            b1.Property<int>("KSlots")
                                .HasColumnType("integer");

                            b1.Property<int>("QbSlots")
                                .HasColumnType("integer");

                            b1.Property<int>("RbSlots")
                                .HasColumnType("integer");

                            b1.Property<int>("SuperFlexSlots")
                                .HasColumnType("integer");

                            b1.Property<bool>("TePremium")
                                .HasColumnType("boolean");

                            b1.Property<int>("TeSlots")
                                .HasColumnType("integer");

                            b1.Property<int>("WrSlots")
                                .HasColumnType("integer");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "ScoringSettings", "Cutline.Core.Entities.League.ScoringSettings#ScoringSettings", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("FumbleLostPoints")
                                .HasColumnType("numeric");

                            b1.Property<decimal>("InterceptionPoints")
                                .HasColumnType("numeric");

                            b1.Property<decimal>("PassingTdPoints")
                                .HasColumnType("numeric");

                            b1.Property<decimal>("PassingYardsPerPoint")
                                .HasColumnType("numeric");

                            b1.Property<decimal>("ReceivingTdPoints")
                                .HasColumnType("numeric");

                            b1.Property<decimal>("ReceivingYardsPerPoint")
                                .HasColumnType("numeric");

                            b1.Property<decimal>("ReceptionPoints")
                                .HasColumnType("numeric");

                            b1.Property<decimal>("RushingTdPoints")
                                .HasColumnType("numeric");

                            b1.Property<decimal>("RushingYardsPerPoint")
                                .HasColumnType("numeric");
                        });

                    b.HasKey("Id");

                    b.ToTable("Leagues");
                });

            modelBuilder.Entity("Cutline.Core.Entities.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("ByeWeek")
                        .HasColumnType("integer");

                    b.Property<string>("EspnId")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("GsisId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset>("LastSyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NflTeam")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("SleeperId")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EspnId");

                    b.HasIndex("GsisId")
                        .IsUnique();

                    b.HasIndex("SleeperId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("Cutline.Core.Entities.RosterSlot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsStarter")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<int>("SlotType")
                        .HasColumnType("integer");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("TeamId");

                    b.ToTable("RosterSlots");
                });

            modelBuilder.Entity("Cutline.Core.Entities.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("EliminatedWeek")
                        .HasColumnType("integer");

                    b.Property<bool>("IsEliminated")
                        .HasColumnType("boolean");

                    b.Property<Guid>("LeagueId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("OwnerUserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("LeagueId", "OwnerUserId")
                        .IsUnique();

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("Cutline.Core.Entities.TeamScore", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Points")
                        .HasColumnType("numeric");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WeekId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.HasIndex("WeekId", "TeamId")
                        .IsUnique();

                    b.ToTable("TeamScores");
                });

            modelBuilder.Entity("Cutline.Core.Entities.WaiverClaim", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AddPlayerId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DropPlayerId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("FaabBid")
                        .HasColumnType("numeric");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WeekId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AddPlayerId");

                    b.HasIndex("DropPlayerId");

                    b.HasIndex("TeamId");

                    b.HasIndex("WeekId");

                    b.ToTable("WaiverClaims");
                });

            modelBuilder.Entity("Cutline.Core.Entities.Week", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("EliminatedTeamId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LeagueId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("WeekNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EliminatedTeamId");

                    b.HasIndex("LeagueId", "WeekNumber")
                        .IsUnique();

                    b.ToTable("Weeks");
                });

            modelBuilder.Entity("Cutline.Core.Entities.RosterSlot", b =>
                {
                    b.HasOne("Cutline.Core.Entities.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cutline.Core.Entities.Team", "Team")
                        .WithMany("RosterSlots")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Cutline.Core.Entities.Team", b =>
                {
                    b.HasOne("Cutline.Core.Entities.League", "League")
                        .WithMany("Teams")
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("League");
                });

            modelBuilder.Entity("Cutline.Core.Entities.TeamScore", b =>
                {
                    b.HasOne("Cutline.Core.Entities.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cutline.Core.Entities.Week", "Week")
                        .WithMany("TeamScores")
                        .HasForeignKey("WeekId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");

                    b.Navigation("Week");
                });

            modelBuilder.Entity("Cutline.Core.Entities.WaiverClaim", b =>
                {
                    b.HasOne("Cutline.Core.Entities.Player", "AddPlayer")
                        .WithMany()
                        .HasForeignKey("AddPlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Cutline.Core.Entities.Player", "DropPlayer")
                        .WithMany()
                        .HasForeignKey("DropPlayerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Cutline.Core.Entities.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Cutline.Core.Entities.Week", "Week")
                        .WithMany("WaiverClaims")
                        .HasForeignKey("WeekId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AddPlayer");

                    b.Navigation("DropPlayer");

                    b.Navigation("Team");

                    b.Navigation("Week");
                });

            modelBuilder.Entity("Cutline.Core.Entities.Week", b =>
                {
                    b.HasOne("Cutline.Core.Entities.Team", "EliminatedTeam")
                        .WithMany()
                        .HasForeignKey("EliminatedTeamId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Cutline.Core.Entities.League", "League")
                        .WithMany("Weeks")
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EliminatedTeam");

                    b.Navigation("League");
                });

            modelBuilder.Entity("Cutline.Core.Entities.League", b =>
                {
                    b.Navigation("Teams");

                    b.Navigation("Weeks");
                });

            modelBuilder.Entity("Cutline.Core.Entities.Team", b =>
                {
                    b.Navigation("RosterSlots");
                });

            modelBuilder.Entity("Cutline.Core.Entities.Week", b =>
                {
                    b.Navigation("TeamScores");

                    b.Navigation("WaiverClaims");
                });
#pragma warning restore 612, 618
        }
    }
}
